---
title: "NUTRISHIELD_Study_II_QTrap_Semiquant_Urine_EDA"
author: "parth doshi"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = TRUE,
                      cache = TRUE)
```

## Exploratory Data Analysis for NUTRISHIELD Study II Q trap Semiquant Urine Sample
## Required library

```{r Library, warning=FALSE, include=FALSE, mesasge=FALSE}
# install required library
library(devtools)
devtools::install_github("sfirke/janitor")

# load Required libraries
library(tidyverse) # meta package of all tidyverse packages
library(janitor) # 
library(ggplot2)
library(corrplot)
library(ggcorrplot)
library(caret)
library(FactoMineR)
library(ggfortify)
library(factoextra)
library(reshape2)
library(moments)
library(skimr)
library(car)
```

## Data importing

```{r message=FALSE, warning=TRUE, paged.print=TRUE}
# Set Working Directory
setwd("C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/R-script/EDA_for_Human_Mother_Milk")

#load Data
QTrap.Semiquant.Data <- read.csv("C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/Study2-Data/NUTRISHIELD_Study_II_QTrap_Semiquant_Urine.csv",sep = ",", skip = 2) 

str(QTrap.Semiquant.Data)
```

## Data cleaning

```{r}
#  Cleaning the data sets 
QTrap.Semiquant.Data <- QTrap.Semiquant.Data %>%
  select(-c(1:7), -c(9:13)) %>% # Select columns with names containing "IU" or "MU" 
  t() %>% # Transpose the data Frame
  as.data.frame() %>%
  row_to_names(1) %>% # Use the first row as column names
  mutate_if(names(.) != "Class", as.double)

# Add a new column named "Samples" with row names
QTrap.Semiquant.Data <-rownames_to_column(QTrap.Semiquant.Data, var = "Samples")

# Print summary of QTrap Semiquant Data
 summary(QTrap.Semiquant.Data)
```
```{r warning=FALSE}

# Calculate the percentage of missing values for each column
missing.percent <- colSums(QTrap.Semiquant.Data == 0 | QTrap.Semiquant.Data == 0.0) / nrow(QTrap.Semiquant.Data) * 100

# Print the percentage of missing values for each column
print(missing.percent)

# Get the names of columns with missing values exceeding 50%
missing.variables <- names(missing.percent[missing.percent > 50])

# Print the names of columns with missing values exceeding 50%
print(missing.variables)


```

### Remove feature with constant value

```{r paged.print=TRUE}
# Assuming your dataset is named 'data'
Qtrap.filterd.data <- QTrap.Semiquant.Data[, !names(QTrap.Semiquant.Data) %in% missing.variables]
skimmed <- skim_to_wide(Qtrap.filterd.data)
skimmed
```

## Data Prepossessing

```{r}
skewness(Qtrap.filterd.data[3:54])
```

```{r}
#scaling Of Data
# using caret lib to preprocess data
#Normalization <- preProcess(Qtrap.filterd.data, method = "BoxCox",na.remove = TRUE )

# standardize the preprocessed data
#Qtrap.filterd.data.normal <- predict(Normalization,Qtrap.filterd.data)

#scaling Of Data
# using caret lib to preprocess data
AutoScaling <- preProcess(Qtrap.filterd.data, method = c("scale","center"),na.remove = TRUE )

# standardize the preprocessed data
Qtrap.filterd.data.scaled <- predict(AutoScaling,Qtrap.filterd.data)


# Replacing the value Infinite value  with 0 
#for (col in names(Qtrap.filterd.data.scaled)) {
#  Qtrap.filterd.data.scaled[[col]][!is.finite(Qtrap.filterd.data.scaled[[col]])] <- 0
#}
#Qtrap.filterd.data.scaled <- cbind(QTrap.Semiquant.Data[1:2],Qtrap.filterd.data.scaled)

# Calculate the skewness of the scaled data
skewness(Qtrap.filterd.data.scaled[3:54])

# Summary statistics
skimmed_normal <-skim(Qtrap.filterd.data.scaled)
skimmed_normal
```

### Visualization of Data 

```{r}
Qtrap.filterd.data.scaled.longA <- gather(Qtrap.filterd.data.scaled[3:25])
Qtrap.filterd.data.scaled.longB <- gather(Qtrap.filterd.data.scaled[26:54])

# box plot after distribution for Subset 
Qtrap.filterd.data.scaled.boxplotA <- ggplot(Qtrap.filterd.data.scaled.longA, aes(x = value, y = key, fill = key))+
  geom_boxplot(outlier.colour = "red", outlier.shape = 1) +
  labs(title = "Qtrap filtered data Boxplot",)
print(Qtrap.filterd.data.scaled.boxplotA)

# box plot after distribution for Subset 
Qtrap.filterd.data.scaled.boxplotB <- ggplot(Qtrap.filterd.data.scaled.longB, aes(x = value, y = key, fill = key))+
  geom_boxplot(outlier.colour = "red", outlier.shape = 1) +
  labs(title = "Qtrap filtered data Boxplot",)
print(Qtrap.filterd.data.scaled.boxplotB)


```

```{r}

Qtrap.filterd.data.scaled.subset.A <- Qtrap.filterd.data.scaled %>% 
  select(-c(26:54))

Qtrap.filterd.data.scaled.subset.B <- Qtrap.filterd.data.scaled %>% 
  select(-c(3:25))

# Box plot of data distribution of each group (Mother , PI , TI)
Qtrap.filterd.data.scaled.subset.A %>%
  gather(key = "feature", value = "value", -Samples, -Class) %>%
  ggplot(aes(x = Class, y = value, fill = Class)) +
  geom_boxplot() +
  facet_wrap(~ feature, scales = "free") +
  labs(x = "Group", y = "Value")


Qtrap.filterd.data.scaled.subset.B %>%
  gather(key = "feature", value = "value", -Samples, -Class) %>%
  ggplot(aes(x = Class, y = value, fill = Class)) +
  geom_boxplot() +
  facet_wrap(~ feature, scales = "free") +
  labs(x = "Group", y = "Value")
```

## EDA

```{r echo=FALSE}
# Principle component Analysis
QTrap.Semiquant.Data.pca <- prcomp(Qtrap.filterd.data.scaled[3:54], scale. = TRUE, center = TRUE)

#Visualization of PCA
fviz_pca_ind(QTrap.Semiquant.Data.pca,
             geom = "point",
             habillage = Qtrap.filterd.data.scaled$Class,
             palette = c( "red", "green2","blue"),
             addEllipses = TRUE,
             ellipse_type = "confidence",
             ggtheme = theme_bw(),
             title = "PCA plot for Qtrap Semiquant biomarkrs")

#Scree plot 
fviz_eig(QTrap.Semiquant.Data.pca, 
         addlabels = TRUE, 
         ylim = c(0, 70),
         main="Figure 5: Scree Plot  Qtrap Semiquant ")

#Graph for variable
fviz_pca_var(QTrap.Semiquant.Data.pca, col.var = "red")
```

#### corelation

```{r echo=FALSE}
# Calculate p-values for each correlation coefficient
p.mat <- cor_pmat(Qtrap.filterd.data.scaled[3:54], method = "pearson")
# calculate correlation matrix
correlationMatrix <- cor(Qtrap.filterd.data.scaled[3:54])
# summarize the correlation matrix
#print(correlationMatrix)
ggcorrplot(
  correlationMatrix,
  hc.order = TRUE,   # Hierarchical clustering for reordering variables
  type = "lower",    # Show only the lower triangle of the correlation matrix
  lab = FALSE        # Show labels for variables   
)
```

### Statistical Test

```{r echo=TRUE}
library(rstatix)

# Factor the  class 
Qtrap.filterd.data.scaled$Class <- factor(Qtrap.filterd.data.scaled$Class)

# define the  Contentious Variables
continuous.vars <- c("`EC-G`", "`1,7-DMU`", "`1-MeHis`", "`1-MU`", "`1-MX`", "`2-Aph`", "`2-FG`",
                    "`3-MeHis`", "`3-MX`", "`4-HPB`", "`5-HMFG`", "ANS", "AsB", "CF", "CARN",
                    "CRN", "`cLeu-Pro`", "`cPro-Val`", "`L-CAR`", "`N-MePYR`", "PB", "TB",
                    "`TF-PX`", "TRIGO", "HBA", "`HBA-S`", "HPAA", "`HPAA-S1`", "`3-HPHPA`",
                    "HPPA", "THPV", "`3,4-DHPAA`", "`DHPV-S`", "`3-HHA`", "`4-HHA`", "`4-MeCAT-S`",
                    "BA", "`CA-S`", "`CAT-S`", "`Et-S`", "FA", "`GA-S`", "HA", "HVAlc", "`HPPA-S`",
                    "`MeGA-S`", "`MePYR-S`", "`2-HPA-S`", "`COU-G`", "`COU-S`", "`SYR-S`", "TAR")

categorial.var <- "Class"

# Perform levene's test
for (Vars in continuous.vars) {
  formula <- as.formula(paste(Vars, "~", categorial.var))
 var_Test <-leveneTest(formula, data = Qtrap.filterd.data.scaled)
  cat("Variable:",Vars, "\n")
  print(var_Test)
  cat("\n")
}

# Perform Kruskal-Wallis test for each variable
for (vars in continuous.vars) {
  formula <- as.formula(paste(vars, "~", categorial.var))
  kruskal_model <- kruskal.test(formula, data = Qtrap.filterd.data.scaled)
  cat("Variable:", vars, "\n")
  print(kruskal_model)
  cat("\n")
}


# Perform Dunn test
for (Vars in continuous.vars) {
  formula <- as.formula(paste(Vars, "~", categorial.var))
  Pairwise_test <-dunn_test(formula, data = Qtrap.filterd.data.scaled)
  cat("Variable:",Vars, "\n")
  print(Pairwise_test)
  cat("\n")
}
```

```{r}
library(ggstatsplot)
library(rlang)

StatBoxplot <- function(y) {
  y_sym <- sym(y)
  plot <- ggbetweenstats(
    data = Qtrap.filterd.data.scaled,
    x = Class,
    y = !!y_sym,
    type = "nonparametric",
    plot.type = "box",
    pairwise.comparisons = TRUE,
    pairwise.display = "all",
    centrality.plotting = FALSE,
    bf.message = FALSE,
    ylab = y
  )
  
  return(plot)
}

StatBoxplot("3-MeHis")
StatBoxplot("HPPA")
StatBoxplot("HVAlc")
```

### Regression

```{r}
# Perform Regression for each continuous variable
for (Vars in continuous.vars) {
  formula <- as.formula(paste(Vars, "~", categorial.var))
  LM.model <-lm(formula, data = Qtrap.filterd.data.scaled)
  cat("Variable:",Vars, "\n")
  print(summary(LM.model))
  cat("\n")
}
```

# feature Selection method

```{r}
set.seed(2000)
# Define the control for recursive feature elimination (RFE) using random forest
control <- rfeControl(functions = rfFuncs, method = "cv", number = 10)

# Run the RFE algorithm
results <- rfe(Qtrap.filterd.data.scaled[, 3:54], Qtrap.filterd.data.scaled[, 2], sizes = c(1:8), rfeControl = control)

# Summarize the results
print(results)

# List the chosen features selected by RFE
predictors(results)


library(Boruta)
# Decide if a variable is important or not using Boruta
boruta_output <- Boruta(Class ~ ., data=na.omit(Qtrap.filterd.data.scaled), doTrace=2)  # perform Boruta search

boruta_signif <- names(boruta_output$finalDecision[boruta_output$finalDecision %in% c("Confirmed", "Tentative")])  # collect Confirmed and Tentative variables

plot(boruta_output, cex.axis=.7, las=2, xlab="", main="Variable Importance")  # plot variable
```