---
title: "NUTRISHIELD_Study_II_SCFA_Urine_EDA"
author: "parth doshi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = TRUE,
                      cache = TRUE)
```

# Exploratory Data Analysis for SCFA Urine Sample

#### Required library

```{r message=FALSE, warning=FALSE, paged_print=TRUE}
# install required library
library(devtools)
#devtools::install_github("sfirke/janitor")
devtools::install_github("SkadiEye/deepTL")

# load Required libraries
library(tidyverse) # meta package of all tidyverse packages
library(janitor)
library(stringr)
library(ggplot2)
library(corrplot)
library(caret)
library(FactoMineR)
library(ggfortify)
library(factoextra)
library(reshape2)
library(gridExtra)
library(Boruta)
library(ggbiplot)
library(ggcorrplot)
library(moments)
library(skimr)
library(car)
```

## Data importing

```{r}
# Set Working Directory
setwd("C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/R-script/EDA_for_Human_Mother_Milk")

#load Data
SCFA_Data <- read.csv("C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/Study2-Data/NUTRISHIELD_Study_II_SCFA_Urine.csv",sep = ";", skip = 3) 

str(SCFA_Data)
```

## Data Preprocessing

```{r message=TRUE, warning=FALSE, paged_print=TRUE}
# Data cleaning: Remove the rest of clinical data
SCFA_Data <- SCFA_Data %>%
  select(-c(1:7,9:13,186)) %>%
  # Transpose the data frame
  t() %>%
  # Convert the transposed data frame to a regular data frame
  as.data.frame() %>%
  # Set the first row as column names
  row_to_names(1) %>%
  # Convert all columns to numeric except the "Class" column
  mutate_if(names(.) != "Class", as.numeric) %>%
  # Set the "Sample" column as a separate column named "Sample"
  rownames_to_column(var = "Sample") %>%
  # Remove the "(umol/gcreat)" from column names
  rename_with(~str_remove(., "\\s*\\(umol\\/gcreat\\)"), everything())

# Print the summary of the cleaned SCFA_Data
skimmes <- skim(SCFA_Data)
skimmes


# Write the cleaned data to a CSV file
write_csv(SCFA_Data,"C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/Study2-clean-Data/NUTRISHIELD_Study_II_SCFA_Urine.csv")
```

# Data cleaning

```{r message=FALSE, warning=FALSE}
# Drop the Acetic Acid column which has a large number of missing values
SCFA_Data <- SCFA_Data %>%
  select(-Acetic)

# Data Distribution
# Convert the data from wide to long format using the gather() function
SCFA_Data_long <- gather(SCFA_Data[3:13])

# Create a boxplot using ggplot
SCFA_Data_boxplot <- ggplot(SCFA_Data_long, aes(x = value, y = key, fill = key)) +
  geom_boxplot(outlier_colour = "red", outlier_shape = 1) +
  labs(title = "Raw SCFA Data Boxplot")

# Print the boxplot
print(SCFA_Data_boxplot)

# Calculate the skewness of the columns in SCFA_Data
skewness(SCFA_Data[3:13])
```

### Normalization of the Data

```{r}
# Apply scaling to the data
# using caret lib to preprocess data
AutoScaling <- preProcess(SCFA_Data, method = c("scale","center"),na.remove = TRUE )

# standardize the preprocessed data
SCFA_Data_scaled <- predict(AutoScaling,SCFA_Data)

# Summary statistics after Scaling
skimmes_normal <- skim_to_list(SCFA_Data_scaled)
skimmes_normal

# Calculate the skewness of the scaled data
skewness(SCFA_Data_scaled[3:13])


# Convert the data from wide to long format using the gather() function
SCFA_Data_scaled_long <- gather(SCFA_Data_scaled[3:13])

# Create a boxplot of the scaled data using ggplot
SCFA_Data_scaled_boxplot <- ggplot(SCFA_Data_scaled_long, aes(x = value, y = key, fill = key)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 1) +
  labs(title = "Scaled SCFA Data Boxplot")

# Print the boxplot
print(SCFA_Data_scaled_boxplot)
```

```{r}
# Box plot of comparative analysis for each group (Mother, PI, TI)

# Convert the data to long format using gather()
SCFA_Data_scaled %>%
  gather(key = "feature", value = "value", -Sample, -Class) %>%

  # Create a boxplot using ggplot
  ggplot(aes(x = Class, y = value, fill = Class)) +
  geom_boxplot() +

  # Create separate plots for each feature using facet_wrap()
  facet_wrap(~ feature, scales = "free") +

  # Set the x-axis label as "Group" and y-axis label as "Value"
  labs(x = "Group", y = "Value")

```

```{r}
# Remove the features which as large no of outliers seen in above box plot 
SCFA_Data_scaled <- SCFA_Data_scaled %>% 
   select(-Isovaleric,-Valeric,-Propionic)
```

# EDA

##### Principle component Analysis

```{r}
# Perform PCA on the scaled data
SCFA_Data_scaled_pca <- prcomp(SCFA_Data_scaled[3:10], scale = FALSE, center = FALSE)

# Visualization of PCA

# Plot the individuals (samples) in the PCA space
fviz_pca_ind(SCFA_Data_scaled_pca,
             geom = "point",
             habillage = SCFA_Data_scaled$Class,
             palette = c("blue", "red", "green"),
             addEllipses = FALSE,
             ggtheme = theme_bw(),
             title = "PCA plot for SCFA biomarkers")

# Scree plot to visualize the explained variance by each principal component
fviz_eig(SCFA_Data_scaled_pca,
         addlabels = TRUE,
         ylim = c(0, 70),
         main = "Scree Plot SCFA Data")

# Graph showing the contribution of variables to each principal component
fviz_pca_var(SCFA_Data_scaled_pca, col_var = "red")
```

### correlation

```{r}
# Calculate p-values for each correlation coefficient
p_mat <- cor_pmat(SCFA_Data_scaled[3:10], method = "pearson")

# Calculate correlation matrix using Pearson correlation
correlationMatrix <- cor(SCFA_Data_scaled[3:10], method = "pearson")

# Visualize the correlation matrix using ggcorrplot
ggcorrplot(
  correlationMatrix,
  hc.order = TRUE,   # Hierarchical clustering for reordering variables
  type = "lower",    # Show only the lower triangle of the correlation matrix
  lab = TRUE,        # Show labels for variables
  p.mat = p_mat,      # Overlay p-values on the plot
  sig.level = 0.05,
)

```

### Covariance

```{r}
# Performing Covariance 
cov_df <- cov(SCFA_Data_scaled[sapply(SCFA_Data_scaled,is.numeric)], method = "pearson")

# Covnverting Covariance to Correlation 
cov_df <- cov2cor(cov_df)
cov_df_long <- melt(cov_df)


# Create the covariance plot using ggplot2
plot <- ggplot(cov_df_long, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient(high = "red", low = "white") +
  geom_text(aes(label = paste0(round(value * 100, 2))), color = "black", size = 3) +
  labs(title = "Covariance Heatmap",
       x = "Variable 1",
       y = "Variable 2")


print(plot)
```

### Statistical Test

```{r}
library(rstatix)
# Define the Continuous Variables and Categorial Variable
continuous_vars <- c("Isobutyric", "Butyric", "`2-Me-butyric`", "Caproic", "Heptanoic", "Valine", "Leucine", "Isoleucine")
categorical_var <- "Class"


# perform levene's test to see if all group has equal variance

# Update the levels of the Class variable
SCFA_Data_scaled$Class <- factor(SCFA_Data_scaled$Class)

for (vars in continuous_vars) {
  formula <- as.formula(paste(vars, "~", categorical_var))
  var_test <- leveneTest(formula, data = SCFA_Data_scaled)
  cat("Variable:", vars, "\n")
  print(var_test)
  cat("\n")
}

# Perform Kruskal-Wallis test for each variable
for (vars in continuous_vars) {
  formula <- as.formula(paste(vars, "~", categorical_var))
  kruskal_model <- kruskal.test(formula, data = SCFA_Data_scaled)
  cat("Variable:", vars, "\n")
  print(kruskal_model)
  cat("\n")
}

# Perform pairwise dunn test and display summary for each model
for (var in continuous_vars) {
  formula <- as.formula(paste(var, "~", categorical_var))
  pairwise_test <- dunn_test(formula, data = SCFA_Data_scaled, p.adjust.method = "bonferroni")
  cat("Variable:", var, "\n")
  print(pairwise_test)
  cat("\n")
}

```

### Regression

```{r}
# Perform Regression for each continuous variable
for (Vars in continuous_vars) {
  formula <- as.formula(paste(Vars, "~", categorical_var))
  LM_model <-lm(formula, data = SCFA_Data_scaled)
  cat("Variable:",Vars, "\n")
  print(summary(LM_model))
  cat("\n")
}
```

## Feature selection

```{r}
set.seed(123)

# Update the levels of the Class variable
SCFA_Data_scaled$Class <- factor(SCFA_Data_scaled$Class)

# Define the control for recursive feature elimination (RFE) using random forest
control <- rfeControl(functions = rfFuncs, method = "cv", number = 10)

# Run the RFE algorithm
results <- rfe(SCFA_Data_scaled[, 3:10], SCFA_Data_scaled[, 2], sizes = c(1:8), rfeControl = control)

# Summarize the results
print(results)

# List the chosen features selected by RFE
predictors(results)


library(Boruta)
# Decide if a variable is important or not using Boruta
boruta_output <- Boruta(Class ~ ., data=na.omit(SCFA_Data_scaled), doTrace=2)  # perform Boruta search

boruta_signif <- names(boruta_output$finalDecision[boruta_output$finalDecision %in% c("Confirmed", "Tentative")])  # collect Confirmed and Tentative variables

plot(boruta_output, cex_axis=7, las=2, xlab="", main="Variable Importance")  # plot variable
```


```{r}
library(ggstatsplot)
library(rlang)

StatBoxplot <- function(y) {
  y_sym <- sym(y)
  plot <- ggbetweenstats(
    data = SCFA_Data_scaled,
    x = Class,
    y = !!y_sym,
    type = "nonparametric",
    plot.type = "box",
    pairwise.comparisons = TRUE,
    pairwise.display = "all",
    centrality.plotting = FALSE,
    bf.message = FALSE,
    ylab = y
  )
  
  return(plot)
}


mat <- matrix(1:4, 3, 4 ,byrow = TRUE)

variables <- c("Isobutyric", "Butyric", "2-Me-butyric", "Caproic", "Heptanoic", "Valine", "Leucine", "Isoleucine")

layout(mat)
StatBoxplot(y = "Isobutyric")
StatBoxplot(y = "Butyric")
StatBoxplot(y = "2-Me-butyric")
StatBoxplot(y = "Caproic")
StatBoxplot(y = "Valine")
StatBoxplot(y = "Heptanoic")
StatBoxplot(y = "Leucine")
StatBoxplot(y = "Isoleucine")
```