---
title: "Month Series"
author: "Parth Doshi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      dpi = 500,
                      fig.height=8,fig.width = 11, dev='png', cache = TRUE)
```

## Required Library

```{r message=FALSE, warning=FALSE}
#install.packages("pcutils")

library(tidyverse) # meta package of all tidyverse packages
library(janitor)
library(stringr)
library(caret)
library(ggplot2)
library(pcutils)
library(zoo)
library(corrplot)
library(caret)
library(ggcorrplot)
```


## Common Function 

```{r}
# Define the function to calculate the average and SD for a given parameter
Average_Urine <- function(Data, Parameter) {
  result_df <- Data %>%
    group_by(Type, NewClass, Month) %>%
    summarise(
      Mean = mean(!!sym(Parameter)),  # Convert parameter to symbol and unquote it
      SD = sd(!!sym(Parameter)),      # Convert parameter to symbol and unquote it
      .groups = "drop"                # To avoid issues with tibbles in older versions of dplyr
    )
  return(result_df)
}

# Define the function to calculate the average and SD for a given parameter with orginal class

Average_Urine_Class <- function(Data, Parameter) {
  result_df <- Data %>%
    group_by(Class, Month) %>%
    summarise(
      Mean = mean(!!sym(Parameter)),  # Convert parameter to symbol and unquote it
      SD = sd(!!sym(Parameter)),      # Convert parameter to symbol and unquote it
      .groups = "drop"                # To avoid issues with tibbles in older versions of dplyr
    )
  return(result_df)
}

# Define the function to calculate the average and SD for a given parameter
Average_MILK <- function(Data, Parameter) {
  result_df <- Data %>%
    group_by(NewClass,Month) %>%
    summarise(
      Mean = mean(!!sym(Parameter)),  # Convert parameter to symbol and unquote it
      SD = sd(!!sym(Parameter)),      # Convert parameter to symbol and unquote it
      .groups = "drop"                # To avoid issues with tibbles in older versions of dplyr
    )
  return(result_df)
}
```




## Short chain Fatty Acid

```{r}
# Load Data Sets
NSII_SCFA_Urine <- read.csv("C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/NSII_Corrected_and_Clean_Data/NSII_SCFA_Urine.csv", sep = ",")

NSII_SCFA_Urine <- as.data.frame(NSII_SCFA_Urine[2:19])
str(NSII_SCFA_Urine)
```

##### Data PreProcessing 

```{r message=TRUE, warning=TRUE}
# Min MAX Scaling
#PreProcess <- preProcess(NSII_SCFA_Urine, method = "range")
#NSII_SCFA_Urine <- predict(PreProcess, NSII_SCFA_Urine)

# Replace "CEN" and "RBW" with 0, and convert other Month points to numeric
NSII_SCFA_Urine$Month <- as.numeric(ifelse(NSII_SCFA_Urine$Month %in% c("CEN", "RBW"), 0, NSII_SCFA_Urine$Month))

# Removing the Acetic Acid column as measure of Values Are Missing 
NSII_SCFA_Urine <- NSII_SCFA_Urine %>% 
  select(-Acetic,-Class)

# Sort the data first by 'ID' and then by 'Month'
NSII_SCFA_Urine_sorted <- arrange(NSII_SCFA_Urine,Type , ID, Month)


# Create an empty list to store the results for each parameter
SCFA_list <- list()

SCF_acids <- colnames(NSII_SCFA_Urine_sorted[2:12])

for (Acids in SCF_acids) {
  SCFA_list[[Acids]] <- Average_Urine(NSII_SCFA_Urine_sorted, Acids)
}

# Combine all data frames in the 'result_list' into one data frame
SCFA_df <- bind_rows(SCFA_list, .id = "SCFA_Acids")

# Rename the column to 'SCFA_Acids'
colnames(SCFA_df)[1] <- "SCFA_Acids"

SCFA_df <- replace(SCFA_df, is.na(SCFA_df), 0)

SCFA_df
```

## Time plot SCFA 

```{r}
ggplot(SCFA_df, aes(x = Month, y = Mean, color = NewClass, group = NewClass)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2, alpha = 0.6) +  
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD), width = 0.4, alpha = 0.7) +  # Make error bars slightly transparent
  facet_wrap(~ SCFA_Acids, scales = "free") +
  labs(x = "Month", y = "Mean", color = "Class & Urine Type Combination") +
  theme_minimal()
```
## Qtrap Biomarkers

```{r}
NSIIQ_Targeted_Urine <- read.csv("C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/NSII_Corrected_and_Clean_Data/NSII_Qtrap_Targeted_Urine.csv", sep = ",")

str(NSIIQ_Targeted_Urine)
```

### Data preProcessing 

```{r warning=FALSE}

NSIIQ_Targeted_Urine$Type[NSIIQ_Targeted_Urine$Type == "IU2"] <- "IU"

# Replace "CEN" and "RBW" with 0, and convert other Month points to numeric
NSIIQ_Targeted_Urine$Month <- as.numeric(ifelse(NSIIQ_Targeted_Urine$Month %in% c("CEN", "RBW"), 0, NSIIQ_Targeted_Urine$Month))


# Sort the data first by 'ID' and then by 'Month'
NSIIQ_Targeted_Urine_sorted <- arrange(NSIIQ_Targeted_Urine[,-c(1,3)], Type, ID, Month)


# Create an empty list to store the results for each parameter
Targeted_list <- list()

QT_Biomarkers <- colnames(NSIIQ_Targeted_Urine_sorted[2:28])

for (BM in QT_Biomarkers) {
  Targeted_list[[BM]] <- Average_Urine(NSIIQ_Targeted_Urine_sorted, BM)
}

# Combine all data frames in the 'result_list' into one data frame
Targeted_df <- bind_rows(Targeted_list, .id = "Targeted_Biomarkers")

# Rename the column to 'Parameter'
colnames(Targeted_df)[1] <- "Targeted_Biomarkers"

```

### Time Plot with New Class And Type of urine

```{r}
ggplot(Targeted_df, aes(x = Month, y = Mean, color = NewClass, group = NewClass)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD), width = 0.1) +
  facet_wrap(~ Targeted_Biomarkers, scales = "free") +
  labs(x = "Month", y = "Mean", color = "NewClass_Type Combination") +
  theme_minimal()
```

## MIRIS MILK DATA

```{r}
NSII_MIRIS_HM <- read.csv("C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/NSII_Corrected_and_Clean_Data/NSII_MIRIS_HM_Subset.csv", sep = ",")

str(NSII_MIRIS_HM)
```

```{r}
# Replace "Typo_VALUE" with "NEW_VALUE" in the "Month" column
NSII_MIRIS_HM$Month[NSII_MIRIS_HM$Month == "6.1"] <- "6"
NSII_MIRIS_HM$Month[NSII_MIRIS_HM$Month == "L2"] <- "6"
NSII_MIRIS_HM$Month[NSII_MIRIS_HM$Month == "2B"] <- "2"
NSII_MIRIS_HM$ID[NSII_MIRIS_HM$ID == "P07.6"] <- "P7"
NSII_MIRIS_HM$ID[NSII_MIRIS_HM$ID == "T54.1HM"] <- "T54"


# Replace "CEN" and "RBW" with 0, and convert other Month points to numeric
NSII_MIRIS_HM$Month <- as.numeric(ifelse(NSII_MIRIS_HM$Month %in% c("CEN", "RBW"), 0, NSII_MIRIS_HM$Month))

# Sort the data first by 'ID' and then by 'Month'
NSII_MIRIS_HM_sorted <- arrange(NSII_MIRIS_HM[,-c(1:2)], ID, Month)
NSII_MIRIS_HM_sorted$Month[is.na(NSII_MIRIS_HM_sorted$Month)] <- "2"

# Create an empty list to store the results for each parameter
result_list <- list()

parameters <- colnames(NSII_MIRIS_HM_sorted[2:7])

for (par in parameters) {
  result_list[[par]] <- Average_MILK(NSII_MIRIS_HM_sorted, par)
}

# Combine all data frames in the 'result_list' into one data frame
MIRIS_df <- bind_rows(result_list, .id = "Parameter")

# Rename the column to 'Parameter'
colnames(MIRIS_df)[1] <- "Parameter"
```

## Time Plot 

```{r}
# Create the time plot with mean and sd for each type and parameter
ggplot(MIRIS_df, aes(x = Month, y = Mean, color = NewClass, group = NewClass)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD), width = 0.1) +
  facet_wrap(. ~ Parameter, scales = "free") +
  labs(x = "Month", y = "Mean", color = "Class") +
  theme_minimal()
```

## FAMES in HM

```{r}
NSII_FAMES_HM <- read.csv("C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/NSII_Corrected_and_Clean_Data/NSII_FAMES_HM_Subset.csv", sep = ",")

NSII_FAMES_HM  <- NSII_FAMES_HM  %>% 
  select(-1,-Undecanoate,-Tridecanoate,-Tricosanoate,-Heneicosanoate,-Docosanoate,-`cis.10.Pentadecenoic`,-`cis.11.14.17.Eicosatrienoic`)
str(NSII_FAMES_HM)
```


```{r}
# Changing the Naming Errors in data
NSII_FAMES_HM$Month[NSII_FAMES_HM$Month == "2B"] <- "2"
NSII_FAMES_HM$Month[NSII_FAMES_HM$Month == "R"] <- "RBW"
NSII_FAMES_HM$Month[NSII_FAMES_HM$Month == "C"] <- "CEN"
NSII_FAMES_HM$Month[NSII_FAMES_HM$Month == "2B"] <- "2"


# Replace "CEN" and "RBW" with 0, and convert other Month points to numeric
NSII_FAMES_HM$Month <- as.numeric(ifelse(NSII_FAMES_HM$Month %in% c("CEN", "RBW"), 0, NSII_FAMES_HM$Month))

 # Sort the data first by 'ID' and then by 'Month'
NSII_FAMES_HM_sorted <- arrange(NSII_FAMES_HM, ID, Month)

# create a new column with Type of Milk to distinguish between IDs Starting With "P" as Preterm And "T" as Term
NSII_FAMES_HM_sorted$Type <- ifelse(substr(NSII_FAMES_HM_sorted$ID, 1,1) == "P", "Preterm", "Term")


# Create an empty list to store the results for each parameter
FAMES_list <- list()

fatty_acids <- colnames(NSII_FAMES_HM_sorted[3:31])

for (Acids in fatty_acids) {
  FAMES_list[[Acids]] <- Average_MILK(NSII_FAMES_HM_sorted, Acids)
}

# Combine all data frames in the 'result_list' into one data frame
FAMES_df <- bind_rows(FAMES_list, .id = "Fatty_Acids")

# Rename the column to 'Parameter'
colnames(FAMES_df)[1] <- "Fatty_Acids"
```

```{r}
# Create the time plot with mean and sd for each type and parameter
ggplot(FAMES_df, aes(x = Month, y = Mean, color = NewClass, group = NewClass)) +
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD), width = 0.1) +
  facet_wrap(. ~ Fatty_Acids, scales = "free") +
  labs(x = "Month", y = "Mean", color = "Class") +
  theme_minimal()
```

## Qtrap Semiquantatnt data

```{r}
NSIIQ_Semiquant_Urine <- read.csv("C:/Users/Parth Doshi/Dropbox/Nutrishield_Study_II_Project (ParthD thesis)/NSII_Corrected_and_Clean_Data/NSII_Qtrap_Semiquant_Urine.csv", sep = ",")

str(NSIIQ_Semiquant_Urine)
```

### Data PreProcessing 

```{r warning=FALSE}
# Calculate the percentage of missing values for each column
missing_percent <- colSums(NSIIQ_Semiquant_Urine == 0 | NSIIQ_Semiquant_Urine == 0.0) / nrow(NSIIQ_Semiquant_Urine) * 100

# Print the percentage of missing values for each column
#print(missing_percent)

# Get the names of columns with missing values exceeding 50%
missing_variables <- names(missing_percent[missing_percent > 50])
NSIIQ_Semiquant_Urine <- NSIIQ_Semiquant_Urine[, !names(NSIIQ_Semiquant_Urine) %in% missing_variables]

# Remove rows where "Month" value is character "O"
NSIIQ_Semiquant_Urine <- NSIIQ_Semiquant_Urine[NSIIQ_Semiquant_Urine$Month != "O", ]


# Convert "CEN" and "RBW" to numeric 0
NSIIQ_Semiquant_Urine$Month <- as.numeric(ifelse(NSIIQ_Semiquant_Urine$Month %in% c("CEN", "RBW"), 0, NSIIQ_Semiquant_Urine$Month))

# Sort the data first by 'ID' and then by 'Month'
NSIIQ_Semiquant_Urine_sorted <- arrange(NSIIQ_Semiquant_Urine[-1], ID, Month)


# scale the sorted  data
preprocess <- preProcess(NSIIQ_Semiquant_Urine_sorted, method = c("center","scale"))
NSIIQ_Semiquant_Urine_sorted <- predict(preprocess, NSIIQ_Semiquant_Urine_sorted)
```

```{r}
# Create an empty list to store the results for each parameter
Semiquant_list <- list()

QT_Biomarkers_A <- colnames(NSIIQ_Semiquant_Urine_sorted[3:25])

for (BM in QT_Biomarkers_A) {
  Semiquant_list[[BM]] <- Average_Urine(NSIIQ_Semiquant_Urine_sorted, BM)
}

# Combine all data frames in the 'result_list' into one data frame
Semiquant_df <- bind_rows(Semiquant_list, .id = "Semiquant_Biomarkers")

# Rename the column to 'Parameter'
colnames(Semiquant_df)[1] <- "Semiquant_Biomarkers"
```

```{r}
# Create an empty list to store the results for each parameter
Semiquant_Class_list <- list()

QT_Biomarkers_B <- colnames(NSIIQ_Semiquant_Urine_sorted[26:38])

for (BM in QT_Biomarkers_B) {
  Semiquant_Class_list[[BM]] <- Average_Urine(NSIIQ_Semiquant_Urine_sorted, BM)
}

# Combine all data frames in the 'result_list' into one data frame
Semiquant_df_subset <- bind_rows(Semiquant_Class_list, .id = "Semiquant_Biomarkers")

# Rename the column to 'Parameter'
colnames(Semiquant_df_subset)[1] <- "Semiquant_Biomarkers"
```

### Time Plot With NewClass

```{r fig.height=11, fig.width=12}
ggplot(Semiquant_df, aes(x = Month, y = Mean, color = NewClass, group = NewClass)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2, alpha = 0.6) +  
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD), width = 0.4, alpha = 0.7) +  # Make error bars slightly transparent
  facet_wrap(~ Semiquant_Biomarkers, scales = "free") +
  labs(x = "Month", y = "Mean", color = "Class") +
  theme_minimal()
```
### Time Plot with Orginal Class

```{r}
ggplot(Semiquant_df_subset, aes(x = Month, y = Mean, color = NewClass, group = NewClass)) +
  geom_line(linewidth = 0.9) +
  geom_point(size = 2, alpha = 0.6) +  
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD), width = 0.4, alpha = 0.7) +  # Make error bars slightly transparent
  facet_wrap(~ Semiquant_Biomarkers, scales = "free") +
  labs(x = "Month", y = "Average Concentration", color = "Class") +
  theme_minimal()
```
